modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="${mod_issues_url}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="${mod_display_url}"
authors="${mod_authors}"
displayTest="IGNORE_SERVER_VERSION"
description='''${mod_description}'''

[[dependencies."${mod_id}"]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies."${mod_id}"]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies."${mod_id}"]]
    modId="farmersdelight"
    mandatory=true
    versionRange="${farmersdelight_version_range}"
    ordering="NONE"
    side="BOTH"

[modproperties."${mod_id}"]
    catalogueItemIcon="${catalogue_item_icon}"
